import { Composer } from '../composer/Composer.jsx';
import { ChatPane } from '../chat/ChatPane.jsx';
import { ImagePreviewModal } from '../chat/ImagePreview.jsx';
import { ConnectionRecoveryCard, DocsPanel, Drawer, GitPanel, ToastStack, TopBar } from '../panels/index.js';

export function AppShell({
  shellClass,
  status,
  selectedProject,
  selectedSession,
  connectionState,
  running,
  drawerOpen,
  docsOpen,
  docsBusy,
  docsError,
  gitPanel,
  theme,
  projects,
  expandedProjectIds,
  sessionsByProject,
  loadingProjectId,
  runningById,
  threadRuntimeById,
  completedSessionIds,
  syncing,
  canCreateThreadFromMobile,
  createThreadUnavailableReason,
  recoveryState,
  toasts,
  messages,
  activityClockNow,
  input,
  setInput,
  selectedModel,
  setSelectedModel,
  selectedReasoningEffort,
  setSelectedReasoningEffort,
  selectedSkillPaths,
  permissionMode,
  setPermissionMode,
  attachments,
  fileMentions,
  uploading,
  visibleContextStatus,
  composerRunStatus,
  selectedRuntime,
  queueDrafts,
  previewImage,
  notificationSupported,
  notificationEnabled,
  enableNotifications,
  dismissToast,
  showToast,
  setDrawerOpen,
  setDocsOpen,
  setGitPanel,
  setTheme,
  setPreviewImage,
  toggleSelectedSkill,
  selectSkill,
  clearSelectedSkills,
  addFileMention,
  removeFileMention,
  restoreQueueDraft,
  removeQueueDraft,
  steerQueueDraft,
  handleGitAction,
  handleToggleProject,
  handleSelectSession,
  handleRenameSession,
  handleDeleteSession,
  handleNewConversation,
  handleSync,
  handleConnectDocs,
  handleDisconnectDocs,
  handleOpenDocsHome,
  handleOpenDocsAuth,
  handleRefreshDocs,
  handleRetryConnection,
  handleResetPairing,
  handleShowConnectionStatus,
  handleDeleteMessage,
  handleSubmit,
  handleAbort,
  handleUploadFiles,
  handleRemoveAttachment
}) {
  return (
    <div className={shellClass}>
      <TopBar
        selectedProject={selectedProject}
        selectedSession={selectedSession}
        connectionState={connectionState}
        desktopBridge={status.desktopBridge}
        onMenu={() => setDrawerOpen(true)}
        onOpenDocs={() => setDocsOpen(true)}
        onGitAction={handleGitAction}
        notificationSupported={notificationSupported}
        notificationEnabled={notificationEnabled}
        onEnableNotifications={enableNotifications}
        gitDisabled={!selectedProject || running}
      />
      <Drawer
        open={drawerOpen}
        onClose={() => setDrawerOpen(false)}
        projects={projects}
        selectedProject={selectedProject}
        selectedSession={selectedSession}
        expandedProjectIds={expandedProjectIds}
        sessionsByProject={sessionsByProject}
        loadingProjectId={loadingProjectId}
        runningById={runningById}
        threadRuntimeById={threadRuntimeById}
        completedSessionIds={completedSessionIds}
        onToggleProject={handleToggleProject}
        onSelectSession={handleSelectSession}
        onRenameSession={handleRenameSession}
        onDeleteSession={handleDeleteSession}
        onNewConversation={handleNewConversation}
        onSync={handleSync}
        syncing={syncing}
        theme={theme}
        setTheme={setTheme}
        canCreateThread={canCreateThreadFromMobile}
        createThreadUnavailableReason={createThreadUnavailableReason}
      />
      <DocsPanel
        open={docsOpen}
        docs={status.docs}
        busy={docsBusy}
        error={docsError}
        onClose={() => setDocsOpen(false)}
        onConnect={handleConnectDocs}
        onDisconnect={handleDisconnectDocs}
        onOpenHome={handleOpenDocsHome}
        onOpenAuth={handleOpenDocsAuth}
        onRefresh={handleRefreshDocs}
      />
      <GitPanel
        open={gitPanel.open}
        action={gitPanel.action}
        project={selectedProject}
        onToast={showToast}
        onClose={() => setGitPanel((current) => ({ ...current, open: false }))}
      />
      <ConnectionRecoveryCard
        state={recoveryState}
        onRetry={handleRetryConnection}
        onSync={handleSync}
        onPair={handleResetPairing}
        onStatus={handleShowConnectionStatus}
      />
      <ToastStack toasts={toasts} onDismiss={dismissToast} />
      <ChatPane
        messages={messages}
        selectedSession={selectedSession}
        running={running}
        now={activityClockNow}
        onPreviewImage={setPreviewImage}
        onDeleteMessage={handleDeleteMessage}
      />
      <Composer
        input={input}
        setInput={setInput}
        selectedProject={selectedProject}
        selectedSession={selectedSession}
        onSubmit={handleSubmit}
        running={running}
        onAbort={handleAbort}
        models={status.models}
        selectedModel={selectedModel}
        onSelectModel={setSelectedModel}
        selectedReasoningEffort={selectedReasoningEffort}
        onSelectReasoningEffort={setSelectedReasoningEffort}
        skills={status.skills}
        selectedSkillPaths={selectedSkillPaths}
        onToggleSkill={toggleSelectedSkill}
        onSelectSkill={selectSkill}
        onClearSkills={clearSelectedSkills}
        permissionMode={permissionMode}
        onSelectPermission={setPermissionMode}
        attachments={attachments}
        onUploadFiles={handleUploadFiles}
        onRemoveAttachment={handleRemoveAttachment}
        fileMentions={fileMentions}
        onAddFileMention={addFileMention}
        onRemoveFileMention={removeFileMention}
        uploading={uploading}
        contextStatus={visibleContextStatus}
        runStatus={composerRunStatus ? { ...composerRunStatus, steerable: selectedRuntime?.steerable !== false } : null}
        desktopBridge={status.desktopBridge}
        queueDrafts={queueDrafts}
        onRestoreQueueDraft={restoreQueueDraft}
        onRemoveQueueDraft={removeQueueDraft}
        onSteerQueueDraft={steerQueueDraft}
      />
      <ImagePreviewModal image={previewImage} onClose={() => setPreviewImage(null)} />
    </div>
  );
}
